# Generated by Django 5.2.7 on 2025-11-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان کارت')),
                ('image', models.ImageField(upload_to='donations/cards/', verbose_name='تصویر کارت')),
                ('card_number', models.CharField(max_length=20, verbose_name='شماره کارت')),
                ('sheba_number', models.CharField(max_length=30, verbose_name='شماره شبا')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک پرداخت یا بله')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کارت کمک مردمی',
                'verbose_name_plural': 'کارت\u200cهای کمک مردمی',
                'ordering': ['-created_at'],
            },
        ),
    ]
