# Generated by Django 5.2.7 on 2025-11-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcard',
            name='card_number',
            field=models.CharField(max_length=16, verbose_name='شماره کارت'),
        ),
    ]
