# Generated by Django 6.0b1 on 2025-11-16 07:13

import django_jalali.db.models
import django_resized.forms
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان اطلاعیه')),
                ('content', models.TextField(verbose_name='متن اطلاعیه')),
                ('datetime', models.CharField(verbose_name='تاریخ و ساعت برگزاری')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ برگزاری مراسم')),
                ('location', models.CharField(max_length=255, verbose_name='محل برگزاری')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=False, quality=85, scale=None, size=[600, 800], upload_to='notifications', verbose_name='تصویر')),
                ('tags', taggit.managers.TaggableManager(help_text='تگ\u200cها را با کاما (,) جدا کنید', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='تگ\u200cها')),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه\u200cها',
                'ordering': ['-datetime'],
            },
        ),
    ]
