# Generated by Django 5.2.7 on 2025-11-05 13:39

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now, verbose_name='تاریخ برگزاری مراسم'),
        ),
    ]
