# Generated by Django 5.2.7 on 2025-11-05 13:43

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ برگزاری مراسم'),
        ),
    ]
