# Generated by Django 5.2.7 on 2025-10-25 19:25

import django.db.models.deletion
import django_jalali.db.models
import django_resized.forms
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مراسم')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('date', django_jalali.db.models.jDateField(default=None, verbose_name='تاریخ مراسم')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='تعداد لایک\u200cها')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('tags', taggit.managers.TaggableManager(help_text='برچسب\u200cها را با کاما جدا کنید', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='برچسب\u200cها')),
            ],
            options={
                'verbose_name': 'گزارش روز',
                'verbose_name_plural': 'گزارشات روز',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='متن نظر')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='تعداد لایک\u200cها')),
                ('dislike_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دیسلایک\u200cها')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='report.report')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='reports/%Y/%m/%d/', verbose_name='تصویر')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='report.report')),
            ],
            options={
                'verbose_name': 'تصویر گزارشات',
                'verbose_name_plural': 'تصاویر گزارشات',
            },
        ),
        migrations.CreateModel(
            name='ReportLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_rel', to='report.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'لایک گزارش',
                'verbose_name_plural': 'لایک\u200cهای گزارش',
            },
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='report.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created'], name='report_comm_created_3878b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportlike',
            unique_together={('report', 'user')},
        ),
    ]
