# Generated by Django 6.0b1 on 2025-11-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سئو'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان سئو'),
        ),
    ]
