# Generated by Django 5.2.7 on 2025-10-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reportlike',
            name='report',
        ),
        migrations.RemoveField(
            model_name='report',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='report',
            name='views',
        ),
        migrations.DeleteModel(
            name='CommentReaction',
        ),
        migrations.DeleteModel(
            name='ReportLike',
        ),
    ]
