# Generated by Django 5.2.7 on 2025-10-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='reports', to='report.category', verbose_name='دسته\u200cها'),
        ),
    ]
