# Generated by Django 5.2.7 on 2025-10-16 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportimage',
            options={'verbose_name': 'تصویر گزارشات', 'verbose_name_plural': 'تصاویر گزارشات'},
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='report.report'),
        ),
    ]
