# Generated by Django 6.0b1 on 2025-12-12 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_url', models.URLField(verbose_name='لینک فایل صوتی')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان صوت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات صوت')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='report.report')),
            ],
            options={
                'verbose_name': 'صوت گزارش',
                'verbose_name_plural': 'صوت\u200cهای گزارش',
                'ordering': ['created'],
            },
        ),
    ]
