# Generated by Django 5.2.7 on 2025-10-22 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_reportlike_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد لایک\u200cها'),
        ),
        migrations.CreateModel(
            name='ReportLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_likes', to='report.report')),
            ],
            options={
                'verbose_name': 'لایک گزارش',
                'verbose_name_plural': 'لایک\u200cهای گزارش',
                'unique_together': {('report', 'session_key')},
            },
        ),
    ]
