# Generated by Django 5.2.7 on 2025-10-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_reportimage_options_alter_reportimage_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
