# Generated by Django 5.2.7 on 2025-10-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_reportview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='report',
            name='views',
        ),
    ]
