# Generated by Django 5.2.7 on 2025-10-25 11:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_comment_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='commentreaction',
            name='report_comm_comment_7edfd6_idx',
        ),
        migrations.RenameField(
            model_name='commentreaction',
            old_name='name',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='commentreaction',
            unique_together={('comment', 'user')},
        ),
    ]
