# Generated by Django 5.2.7 on 2025-10-27 16:23

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_category_report_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=85, scale=None, size=[1920, 1080], upload_to='reports/%Y/%m/%d/', verbose_name='تصویر'),
        ),
    ]
