# Generated by Django 5.2.7 on 2025-10-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report_likes_reportlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
