# Generated by Django 5.2.7 on 2025-10-27 16:27

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_reportimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=False, quality=85, scale=None, size=[800, 600], upload_to='reports/%Y/%m/%d/', verbose_name='تصویر'),
        ),
    ]
