# Generated by Django 5.2.7 on 2025-10-25 13:37

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_commentreaction_report_comm_comment_7edfd6_idx_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='برچسب\u200cها را با کاما جدا کنید', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='برچسب\u200cها'),
        ),
    ]
