# Generated by Django 5.2.7 on 2025-10-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_report_likes_remove_report_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد لایک\u200cها'),
        ),
        migrations.AddField(
            model_name='report',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.DeleteModel(
            name='ReportView',
        ),
    ]
