# Generated by Django 6.0b1 on 2025-12-06 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_delete_reportvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_uid', models.CharField(max_length=50, verbose_name='شناسه ویدیو')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان ویدیو')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات ویدیو')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='report.report')),
            ],
            options={
                'verbose_name': 'ویدیو گزارش',
                'verbose_name_plural': 'ویدیوهای گزارش',
                'ordering': ['created'],
            },
        ),
    ]
