# Generated by Django 6.0b1 on 2025-11-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='seo_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='seo_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
