# Generated by Django 5.2.7 on 2025-10-22 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_report_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportlike',
            options={},
        ),
        migrations.RemoveField(
            model_name='reportlike',
            name='created',
        ),
        migrations.AlterField(
            model_name='reportlike',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='report.report'),
        ),
        migrations.AlterField(
            model_name='reportlike',
            name='session_key',
            field=models.CharField(max_length=40),
        ),
    ]
