# Generated by Django 5.2.7 on 2025-10-18 09:47

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_comment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=(1920, 1080), upload_to='reports/%Y/%m/%d/', verbose_name='تصویر'),
        ),
    ]
