# Generated by Django 5.2.7 on 2025-10-22 18:55

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_reportlike_options_remove_reportlike_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislike_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد دیسلایک\u200cها'),
        ),
        migrations.AddField(
            model_name='comment',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد لایک\u200cها'),
        ),
        migrations.AlterField(
            model_name='reportlike',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_rel', to='report.report'),
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='report.comment')),
            ],
            options={
                'unique_together': {('comment', 'session_key')},
            },
        ),
    ]
