# Generated by Django 5.2.7 on 2025-10-17 07:47

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='posts/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پست خبری',
                'verbose_name_plural': 'پست های خبری',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['created'], name='blog_post_created_594d2d_idx')],
            },
        ),
    ]
