# Generated by Django 6.0b1 on 2025-12-06 08:32

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_updated_alter_post_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2025, 12, 6, 12, 2, 53, 895231)),
        ),
    ]
