# Generated by Django 6.0b1 on 2025-12-06 18:07

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2025, 12, 6, 21, 37, 14, 8474)),
        ),
    ]
