# Generated by Django 5.2.7 on 2025-10-31 12:28

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('name', models.CharField(max_length=250, verbose_name='نام')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
            },
        ),
    ]
