# Generated by Django 6.0b1 on 2025-12-06 08:30

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='hero/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام خادم')),
                ('role', models.CharField(max_length=200, verbose_name='سمت / مسئولیت')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=False, quality=85, scale=None, size=[600, 600], upload_to='staff/', verbose_name='تصویر خادم')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
            ],
            options={
                'verbose_name': 'خادم مسجد',
                'verbose_name_plural': 'خادمان مسجد',
                'ordering': ['order'],
            },
        ),
    ]
