# Generated by Django 5.2.7 on 2025-10-27 18:24

import django_jalali.db.models
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrotter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='متن پارچه')),
                ('category', models.CharField(choices=[('شهادت', 'شهادت'), ('ولادت', 'ولادت'), ('همه مناسبت ها', 'همه مناسبت ها')], max_length=50, verbose_name='مناسبت')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('location', models.CharField(max_length=500, verbose_name='محل نگهداری')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('last_checked', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='آخرین استفاده')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='عرض')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='ارتفاع')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=70, scale=None, size=[800, 600], upload_to='inventory')),
            ],
            options={
                'verbose_name': 'پارچه',
                'verbose_name_plural': 'پارچه ها',
                'ordering': ['category', 'text'],
            },
        ),
    ]
