# Generated by Django 5.2.7 on 2025-10-27 18:49

import django_jalali.db.models
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrotter',
            old_name='last_checked',
            new_name='last_used',
        ),
        migrations.CreateModel(
            name='Decorative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('description', models.TextField(max_length=500, verbose_name='توضیحات')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('last_used', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='آخرین استفاده')),
                ('location', models.CharField(max_length=500, verbose_name='محل نگهداری')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=70, scale=None, size=[800, 600], upload_to='inventory')),
            ],
            options={
                'verbose_name': 'دکوری',
                'verbose_name_plural': 'دکوری ها',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='inventory_d_name_9ea3ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='LED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', 'قرمز'), ('green', 'سبز'), ('blue', 'آبی'), ('white', 'سفید')], verbose_name='رنگ')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('location', models.CharField(max_length=500, verbose_name='محل نگهداری')),
                ('last_used', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='آخرین استفاده')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=70, scale=None, size=[800, 600], upload_to='inventory')),
            ],
            options={
                'verbose_name': 'لامپ',
                'verbose_name_plural': 'لامپ ها',
                'ordering': ['color', 'quantity'],
                'indexes': [models.Index(fields=['color', 'quantity'], name='inventory_l_color_157f65_idx')],
            },
        ),
    ]
